name: Check Spelling and URLs

on: [pull_request]

# Kill concurrent jobs from the same PR/branch - only one will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check Spelling
      uses: crate-ci/typos@12c64918956d94e55a2ca8c5cbca111e759f5654 # version 1.13.8
      with:
        files: ./_posts ./pages ./README.md ./index.html

    - name: URLs-checker

      uses: urlstechie/urlchecker-action@0.0.34
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.yml

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # More verbose summary at the end of a run
        verbose: true

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3

        # Google Forms is having enormous timeouts
        timeout: 10

        # Exclude these patterns from the checker
        exclude_patterns: supercomputing.org

        # Exclude these files from the checker
        exclude_files: README.md,SocialNetworks.yml,_config.yml,tests/test_,.github/workflows
